//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Kokturk_Software_And_Hardware_Company
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class Kokturk_SoftwareEntities : DbContext
    {
        public Kokturk_SoftwareEntities()
            : base("name=Kokturk_SoftwareEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Computer_Programming_Languages_Frameworks> Computer_Programming_Languages_Frameworks { get; set; }
        public virtual DbSet<Devices> Devices { get; set; }
        public virtual DbSet<Mobile_Programming_Languages_Frameworks> Mobile_Programming_Languages_Frameworks { get; set; }
        public virtual DbSet<Programming_Languages> Programming_Languages { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
    }
}
