//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Kokturk_Software_And_Hardware_Company
{
    using System;
    using System.Collections.Generic;
    
    public partial class Computer_Programming_Languages_Frameworks
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Computer_Programming_Languages_Frameworks()
        {
            this.Programming_Languages = new HashSet<Programming_Languages>();
        }
    
        public short Computer_Programming_Language_Framework_Id { get; set; }
        public string Computer_Programming_Language_Framework_Name { get; set; }
        public string Computer_Programming_Language_Framework_Description { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Programming_Languages> Programming_Languages { get; set; }
    }
}
