//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Kokturk_Software_And_Hardware_Company
{
    using System;
    using System.Collections.Generic;
    
    public partial class Programming_Languages
    {
        public int Programming_Language_Id { get; set; }
        public Nullable<short> Device_Select { get; set; }
        public string Programming_Languages1 { get; set; }
        public Nullable<short> Mobile_Programming_Languages_Frameworks { get; set; }
        public Nullable<short> Computer_Programming_Languages_Frameworks { get; set; }
    
        public virtual Computer_Programming_Languages_Frameworks Computer_Programming_Languages_Frameworks1 { get; set; }
        public virtual Devices Devices { get; set; }
        public virtual Mobile_Programming_Languages_Frameworks Mobile_Programming_Languages_Frameworks1 { get; set; }
    }
}
